spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/questionnaire_db
    username: root
    password: 123456

server:
  port: 8080
  address: localhost


